/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones = 'Europe/Helsinki';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    align: AlignBlock;
    'board-member-grid': BoardMemberGridBlock;
    calendar: CalendarBlock;
    card: CardBlock;
    collapsible: CollapsibleBlock;
    committee: CommitteeBlock;
    'embed-video': EmbedVideoBlock;
    form: FormBlock;
    'fuksi-year': FuksiYearBlock;
    icon: IconBlock;
    newsletter: NewsletterBlock;
    'official-year': OfficialYearBlock;
    'pdf-viewer': PDFViewerBlock;
    'page-navigation': PageNavigationBlock;
    'two-columns': TwoColumnsBlock;
  };
  collections: {
    'board-members': BoardMember;
    divisions: Division;
    documents: Document;
    fuksis: Fuksi;
    'fuksi-groups': FuksiGroup;
    media: Media;
    'news-item-types': NewsItemType;
    'news-items': NewsItem;
    newsletters: Newsletter;
    'official-roles': OfficialRole;
    officials: Official;
    pages: Page;
    'page-navigations': PageNavigation;
    translations: Translation;
    forms: Form;
    'form-submissions': FormSubmission;
    redirects: Redirect;
    exports: Export;
    users: User;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'board-members': BoardMembersSelect<false> | BoardMembersSelect<true>;
    divisions: DivisionsSelect<false> | DivisionsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    fuksis: FuksisSelect<false> | FuksisSelect<true>;
    'fuksi-groups': FuksiGroupsSelect<false> | FuksiGroupsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'news-item-types': NewsItemTypesSelect<false> | NewsItemTypesSelect<true>;
    'news-items': NewsItemsSelect<false> | NewsItemsSelect<true>;
    newsletters: NewslettersSelect<false> | NewslettersSelect<true>;
    'official-roles': OfficialRolesSelect<false> | OfficialRolesSelect<true>;
    officials: OfficialsSelect<false> | OfficialsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'page-navigations': PageNavigationsSelect<false> | PageNavigationsSelect<true>;
    translations: TranslationsSelect<false> | TranslationsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'main-navigation': MainNavigation;
    footer: Footer;
    'landing-page': LandingPage;
    'partner-section': PartnerSection;
    'newsletter-settings': NewsletterSettings;
  };
  globalsSelect: {
    'main-navigation': MainNavigationSelect<false> | MainNavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'landing-page': LandingPageSelect<false> | LandingPageSelect<true>;
    'partner-section': PartnerSectionSelect<false> | PartnerSectionSelect<true>;
    'newsletter-settings': NewsletterSettingsSelect<false> | NewsletterSettingsSelect<true>;
  };
  locale: 'fi' | 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      sendNewsletter: TaskSendNewsletter;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AlignBlock".
 */
export interface AlignBlock {
  align: 'left' | 'center' | 'right';
  /**
   * Width of the content in percentage (10-100%)
   */
  width: number;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'align';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BoardMemberGridBlock".
 */
export interface BoardMemberGridBlock {
  members: (number | BoardMember)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'board-member-grid';
}
/**
 * Manage board members
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members".
 */
export interface BoardMember {
  id: number;
  name: string;
  role: string;
  image: number | Media;
  email: string;
  telegram?: string | null;
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload and manage media files
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for the image for accessibility. Should be provided in most cases. A good alt text is short, describes the image, and is not redundant.
   */
  alt?: string | null;
  blurDataUrl: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalendarBlock".
 */
export interface CalendarBlock {
  title: string;
  calendars: {
    /**
     * Google Calendar ID (found in calendar settings)
     */
    calendarId: string;
    /**
     * Pick a color
     */
    color: string;
    /**
     * Pick a color
     */
    textColor: string;
    /**
     * You can find all icons on the page https://lucide.dev/icons/
     */
    icon: string[];
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'calendar';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardBlock".
 */
export interface CardBlock {
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Pick a color
   */
  backgroundColor: string;
  /**
   * Pick a color
   */
  textColor: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'card';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CollapsibleBlock".
 */
export interface CollapsibleBlock {
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  isOpenByDefault?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'collapsible';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CommitteeBlock".
 */
export interface CommitteeBlock {
  officialRole: number | OfficialRole;
  id?: string | null;
  blockName?: string | null;
  blockType: 'committee';
}
/**
 * Manage official roles
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "official-roles".
 */
export interface OfficialRole {
  id: number;
  title?: string | null;
  name: number | Translation;
  year: number;
  officials?: (number | Official)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translations".
 */
export interface Translation {
  id: number;
  /**
   * Translation for official roles and divisions for example. Take in account that changing this will change every other document using this translation. If you want to keep the others, create a new translation.
   */
  translation: string;
  type: 'division' | 'officialRole';
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage officials
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "officials".
 */
export interface Official {
  id: number;
  name: string;
  year: number;
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmbedVideoBlock".
 */
export interface EmbedVideoBlock {
  /**
   * YouTube or Vimeo video URL
   */
  videoUrl: string;
  aspectRatio: '16:9' | '4:3' | '1:1';
  id?: string | null;
  blockName?: string | null;
  blockType: 'embed-video';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'form';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage website pages
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Banner image of the page
   */
  bannerImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * The URL path for this page. Will be auto-generated from the title if left empty.
   */
  path: string;
  showTitle?: boolean | null;
  showTableOfContents?: boolean | null;
  showPartners?: boolean | null;
  hidden?: boolean | null;
  boardMember?: (number | BoardMember)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FuksiYearBlock".
 */
export interface FuksiYearBlock {
  /**
   * The fuksi year to display. Purely to filter divisions from correct year.
   */
  year: number;
  /**
   * Select the fuksi groups to display
   */
  fuksiGroups?: (number | FuksiGroup)[] | null;
  /**
   * Select a default image to display there is no image for the fuksi
   */
  defaultImage?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'fuksi-year';
}
/**
 * Manage fuksi groups
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fuksi-groups".
 */
export interface FuksiGroup {
  id: number;
  name: string;
  year: number;
  fuksis: (number | Fuksi)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage fuksis
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fuksis".
 */
export interface Fuksi {
  id: number;
  name: string;
  year: number;
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconBlock".
 */
export interface IconBlock {
  /**
   * You can find all icons on the page https://lucide.dev/icons/
   */
  icon: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'icon';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterBlock".
 */
export interface NewsletterBlock {
  newsletter: number | Newsletter;
  /**
   * Logo shown in the top right corner of the weekly news
   */
  logo: number | Media;
  /**
   * Footer text shown at the bottom of the weekly news
   */
  footer: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsletter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters".
 */
export interface Newsletter {
  id: number;
  /**
   * Title of the newsletter. If not set, the title will be "Kilta tiedottaa {weekNumber}/{year}" in Finnish and "Weekly News {weekNumber}/{year}" in English.
   */
  title: string;
  /**
   * Type of the newsletter
   */
  type: 'weekly' | 'career';
  /**
   * Newsletter week number and year in format "1/25"
   */
  newsletterNumber: string;
  greetings?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  closingWords?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * News items to be included in the newsletter. Only future news items are shown based on the newsletter number.
   */
  newsItems: (number | NewsItem)[];
  /**
   * Whether the newsletter is ready to be sent. The newsletter will be sent automatically when this is checked at the time specified below or the next clock hour. Unchecking will cancel the scheduled email. Remember to save the newsletter when changing this.
   */
  readyToSend?: boolean | null;
  /**
   * The time of day to send the newsletter. Make sure the time is in the future, else it will be sent at the next clock hour.
   */
  sendTime?: string | null;
  sendTime_tz?: SupportedTimezones;
  /**
   * Whether the newsletter has been sent
   */
  sent?: boolean | null;
  jobId?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-items".
 */
export interface NewsItem {
  id: number;
  title: string;
  /**
   * The type of news item
   */
  type: number | NewsItemType;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  date: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-item-types".
 */
export interface NewsItemType {
  id: number;
  label: string;
  /**
   * Unique identifier for the type (e.g., "guild-events")
   */
  value: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OfficialYearBlock".
 */
export interface OfficialYearBlock {
  /**
   * The year to display. Purely to filter divisions from correct year.
   */
  year: number;
  /**
   * Show officials from a specified divisions
   */
  divisions: {
    /**
     * Select the division to show officials from
     */
    division: number | Division;
    /**
     * Pick a color
     */
    backgroundColor: string;
    /**
     * Pick a color
     */
    textColor: string;
    id?: string | null;
  }[];
  /**
   * Select a default image to display there is no image for the official
   */
  defaultImage?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'official-year';
}
/**
 * Manage divisions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "divisions".
 */
export interface Division {
  id: number;
  title?: string | null;
  name: number | Translation;
  year: number;
  officialRoles?: (number | OfficialRole)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PDFViewerBlock".
 */
export interface PDFViewerBlock {
  /**
   * Select a document to display
   */
  document: number | Document;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pdf-viewer';
}
/**
 * Upload and manage PDF files
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  /**
   * Upload a thumbnail image for the document
   */
  thumbnail?: (number | null) | Media;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageNavigationBlock".
 */
export interface PageNavigationBlock {
  /**
   * Select a page navigation to display
   */
  pageNavigation: number | PageNavigation;
  /**
   * Select a style to display the page navigation
   */
  style: 'links' | 'blocks';
  id?: string | null;
  blockName?: string | null;
  blockType: 'page-navigation';
}
/**
 * Manage website page navigations
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-navigations".
 */
export interface PageNavigation {
  id: number;
  title: string;
  pages?:
    | {
        label: string;
        page: number | Page;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoColumnsBlock".
 */
export interface TwoColumnsBlock {
  /**
   * If true, the right column will be below the left column on mobile.
   */
  wrapOnMobile?: boolean | null;
  /**
   * The layout of the columns. On mobile, the layout will be 100% if wrapOnMobile is true.
   */
  layout:
    | 'grid-cols-[1fr_1fr]'
    | 'grid-cols-[1fr_2fr]'
    | 'grid-cols-[2fr_1fr]'
    | 'grid-cols-[1fr_3fr]'
    | 'grid-cols-[3fr_1fr]';
  contentLeft: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  contentRight: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'two-columns';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Give the path to redirect from. This should be the relative path to the page, e.g. "/kiltajarjestys" to redirect all locales or "/fi/kiltajarjestys" or "/en/kiltajarjestys" to redirect only one locale of the Kiltajärjestys page.
   */
  from: string;
  to?: {
    /**
     * Use a internal link to redirect to pages inside the Guild website. Otherwise, use a custom URL.
     */
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  sort?: string | null;
  locale?: ('all' | 'fi' | 'en') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  sub?: string | null;
  email: string;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish' | 'sendNewsletter';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        parent?: {
          taskSlug?: ('inline' | 'schedulePublish' | 'sendNewsletter') | null;
          taskID?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish' | 'sendNewsletter') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'board-members';
        value: number | BoardMember;
      } | null)
    | ({
        relationTo: 'divisions';
        value: number | Division;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'fuksis';
        value: number | Fuksi;
      } | null)
    | ({
        relationTo: 'fuksi-groups';
        value: number | FuksiGroup;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'news-item-types';
        value: number | NewsItemType;
      } | null)
    | ({
        relationTo: 'news-items';
        value: number | NewsItem;
      } | null)
    | ({
        relationTo: 'newsletters';
        value: number | Newsletter;
      } | null)
    | ({
        relationTo: 'official-roles';
        value: number | OfficialRole;
      } | null)
    | ({
        relationTo: 'officials';
        value: number | Official;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'page-navigations';
        value: number | PageNavigation;
      } | null)
    | ({
        relationTo: 'translations';
        value: number | Translation;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'exports';
        value: number | Export;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: number | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members_select".
 */
export interface BoardMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  image?: T;
  email?: T;
  telegram?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "divisions_select".
 */
export interface DivisionsSelect<T extends boolean = true> {
  title?: T;
  name?: T;
  year?: T;
  officialRoles?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  thumbnail?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fuksis_select".
 */
export interface FuksisSelect<T extends boolean = true> {
  name?: T;
  year?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fuksi-groups_select".
 */
export interface FuksiGroupsSelect<T extends boolean = true> {
  name?: T;
  year?: T;
  fuksis?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  blurDataUrl?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-item-types_select".
 */
export interface NewsItemTypesSelect<T extends boolean = true> {
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-items_select".
 */
export interface NewsItemsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  content?: T;
  date?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters_select".
 */
export interface NewslettersSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  newsletterNumber?: T;
  greetings?: T;
  closingWords?: T;
  newsItems?: T;
  readyToSend?: T;
  sendTime?: T;
  sendTime_tz?: T;
  sent?: T;
  jobId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "official-roles_select".
 */
export interface OfficialRolesSelect<T extends boolean = true> {
  title?: T;
  name?: T;
  year?: T;
  officials?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "officials_select".
 */
export interface OfficialsSelect<T extends boolean = true> {
  name?: T;
  year?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  bannerImage?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  path?: T;
  showTitle?: T;
  showTableOfContents?: T;
  showPartners?: T;
  hidden?: T;
  boardMember?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-navigations_select".
 */
export interface PageNavigationsSelect<T extends boolean = true> {
  title?: T;
  pages?:
    | T
    | {
        label?: T;
        page?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translations_select".
 */
export interface TranslationsSelect<T extends boolean = true> {
  translation?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  sort?: T;
  locale?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  sub?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        parent?:
          | T
          | {
              taskSlug?: T;
              taskID?: T;
            };
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Main navigation menu items
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-navigation".
 */
export interface MainNavigation {
  id: number;
  title: string;
  logo: number | Media;
  items: {
    label: string;
    type: 'page' | 'external';
    page?: (number | null) | Page;
    url?: string | null;
    children?:
      | {
          label: string;
          type: 'page' | 'external';
          page?: (number | null) | Page;
          url?: string | null;
          subchildren?:
            | {
                label: string;
                type: 'page' | 'external';
                page?: (number | null) | Page;
                url?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Footer content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * The main content of the footer (address, contact info, etc.)
   */
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Social media links. Add the link to the social media profile/page and the correct icon will be automatically added.
   */
  socials?: string[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Settings for the landing page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page".
 */
export interface LandingPage {
  id: number;
  /**
   * Banner images of the landing page slideshow
   */
  bannerImages: (number | Media)[];
  /**
   * Announcement for the landing page
   */
  announcement: {
    /**
     * Content of the announcement
     */
    content?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Pick a color
     */
    color: string;
    /**
     * Pick a color
     */
    textColor: string;
  };
  calendar: {
    calendars: {
      /**
       * Google Calendar ID (found in calendar settings)
       */
      calendarId: string;
      /**
       * Pick a color
       */
      color: string;
      /**
       * Pick a color
       */
      textColor: string;
      /**
       * You can find all icons on the page https://lucide.dev/icons/
       */
      icon: string[];
      id?: string | null;
    }[];
    /**
     * Maximum number of events to display
     */
    maxEvents: number;
  };
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Partner organizations and their logos
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-section".
 */
export interface PartnerSection {
  id: number;
  title: string;
  partners: {
    name: string;
    link: string;
    logo: number | Media;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Settings for the weekly and career newsletters
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-settings".
 */
export interface NewsletterSettings {
  id: number;
  weekly: {
    /**
     * Logo to be used in the newsletter
     */
    logo: number | Media;
    /**
     * Footer text for the newsletter
     */
    footer?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Sender email for the newsletter
     */
    senderEmail: string;
    /**
     * Recipient email for the newsletter
     */
    recipientEmail: string;
    /**
     * Weekly page for the newsletter. Linked to the Telegram message.
     */
    weeklyPage: number | Page;
    /**
     * Telegram bot token for the newsletter. Get it from @BotFather
     */
    telegramBotToken: string;
    /**
     * Telegram channel name for the newsletter. For example: @fktieto
     */
    telegramChannelId: string;
  };
  career: {
    /**
     * Footer text for the newsletter
     */
    footer?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Sender email for the newsletter
     */
    senderEmail: string;
    /**
     * Recipient email for the newsletter
     */
    recipientEmail: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-navigation_select".
 */
export interface MainNavigationSelect<T extends boolean = true> {
  title?: T;
  logo?: T;
  items?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        children?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              subchildren?:
                | T
                | {
                    label?: T;
                    type?: T;
                    page?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  content?: T;
  socials?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page_select".
 */
export interface LandingPageSelect<T extends boolean = true> {
  bannerImages?: T;
  announcement?:
    | T
    | {
        content?: T;
        color?: T;
        textColor?: T;
      };
  calendar?:
    | T
    | {
        calendars?:
          | T
          | {
              calendarId?: T;
              color?: T;
              textColor?: T;
              icon?: T;
              id?: T;
            };
        maxEvents?: T;
      };
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-section_select".
 */
export interface PartnerSectionSelect<T extends boolean = true> {
  title?: T;
  partners?:
    | T
    | {
        name?: T;
        link?: T;
        logo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-settings_select".
 */
export interface NewsletterSettingsSelect<T extends boolean = true> {
  weekly?:
    | T
    | {
        logo?: T;
        footer?: T;
        senderEmail?: T;
        recipientEmail?: T;
        weeklyPage?: T;
        telegramBotToken?: T;
        telegramChannelId?: T;
      };
  career?:
    | T
    | {
        footer?: T;
        senderEmail?: T;
        recipientEmail?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: 'landing-page' | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendNewsletter".
 */
export interface TaskSendNewsletter {
  input: {
    newsletterId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}